### PR TITLE
added a test application icon

### PR DESCRIPTION
**Pull request by DT5GEN**
Если нужно сделаем лучше

### CODE REVIEW

**Review by DmitrySergienko — APPROVED** [review]
OK!

**Comment by MarDSoul** [comment]
Not OK. Our user is a home user, he isn't go to fitness center. This icon is for professional user workout. Need more simple icon, such as: [example_simple_icon](https://drive.google.com/file/d/1FDu9STIFjue1_ehfubx0EhWomUHgVuWc/view?usp=sharing)

**Review by Pushin1007 — COMMENTED** [review]
A small picture with a lot of information is not very good. Please do just biceps as an example

**Comment by DmitrySergienko** [comment]
I think we can close this old request!? The launch icon has been updated with splash screen, If required the icon design can be change, in this case is better to open new task.

**Comment by MarDSoul** [comment]
Ok
Resolve conflicts

PS What's a problem to find icon? Go to site with free images, find by keyword and choose some simple icon. For example [find 
 by "workout"](https://pixabay.com/vectors/search/workout/)

**Comment by DmitrySergienko** [comment]
The Launch Icon has been changed already with Splash screen. Install the app to your device and you can see how it works now. The emulator does not show. This is old Pull request already has become not actual.

**Pull request closed without merging**
