### PR TITLE
Bottom navigation view

### PR DESCRIPTION
**Pull request by DmitrySergienko**
Add bottom navigation view

### CODE REVIEW

**Comment by DmitrySergienko** [comment]
Most of conflicts relate to small changings in empty fragments.

**Review by MarDSoul — CHANGES_REQUESTED** [review]
- Resolve conflicts please
- You've used the supportFragmentManager. For what did you add the Navigation component 2 days ago?

**Comment by DmitrySergienko** [comment]
Conflicts were fixed!
I have removed supportFragmentManager and set Navigation components!

**Comment by DmitrySergienko** [comment]
Conflicts were fixed!
I have removed supportFragmentManager and set Navigation components!

**Review by MarDSoul — APPROVED** [review]

**Review by DT5GEN — APPROVED** [review]
It's better than I could have imagined.

**Pull request merged**
