### PR TITLE
Navigation graphs with splash screen & empty frags attached

### PR DESCRIPTION
**Pull request by DmitrySergienko**
navigation graphs attached (navigation logic will be implemented later on)
empty fragment attached 
splash screen attached (picture can be changed later on)

### CODE REVIEW

**Review by MarDSoul — APPROVED** [review]
Need correct splash screen after change launch icon

**Review by DT5GEN — APPROVED** [review]
Watched from a mobile device while everything was normal

**Comment by DmitrySergienko** [comment]
> Need correct splash screen after change launch icon and need correct fragments to extends from BaseFragment after merge previous issue

Ok, as soon as the merge comes

**Review by Pushin1007 — APPROVED** [review]
ok

**Comment by Pushin1007** [comment]
ok

**Pull request merged**
