### PR TITLE
Workout list layout

### PR DESCRIPTION
**Pull request by DmitrySergienko**
Workout list & Workout layouts attached

### CODE REVIEW

**Comment by DmitrySergienko** [comment]
Please don't review! I have to fix conflict!

**Comment by DmitrySergienko** [comment]
Please review conflicts were fixed.

**Review by MarDSoul — CHANGES_REQUESTED** [review]
All dimensions from layouts include in dimens.xml
All pictures .png change to vector format, use standard google icons
Don't create manual TopAppBar, FAB etc. Use [Material Design Components](https://material.io/components?platform=android)

**Comment by DmitrySergienko** [comment]
Icons format has ben changed.
All dimensions are in dimes folder (except of margins, paddings and other constrain attribute related to the concrete layout) 
FAB is original material component! I have change just color make it same how was mentioned in figma example.
The is no manual TopAppBar! All elements individual as was agreed before.

**Review by MarDSoul — APPROVED** [review]

**Comment by MarDSoul** [comment]
I'm too lazy to argue

**Review by DT5GEN — APPROVED** [review]

**Pull request merged**
